class RankData {
  final String name;
  final List<String> songIds;
  final List<int> levelIndexes;
  final int initialHp;
  final int greatDamage;
  final int goodDamage;
  final int missDamage;
  final int healAmount;

  RankData({
    required this.name,
    required this.songIds,
    required this.levelIndexes,
    required this.initialHp,
    required this.greatDamage,
    required this.goodDamage,
    required this.missDamage,
    required this.healAmount,
  });
}

class RankListService {
  List<String> getRankOptions() {
    return [
      '初段',
      '二段',
      '三段',
      '四段',
      '五段',
      '六段',
      '七段',
      '八段',
      '九段',
      '十段',
      '真初段',
      '真二段',
      '真三段',
      '真四段',
      '真五段',
      '真六段',
      '真七段',
      '真八段',
      '真九段',
      '真十段',
      '真皆传',
      '里皆传',
    ];
  }

  RankData? getRankData(String rankName) {
    final rankDataMap = {
      '初段': RankData(
        name: '初段',
        songIds: ['11558', '11086', '404', '628'],
        levelIndexes: [0, 0, 0, 0],
        initialHp: 350,
        greatDamage: 0,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 20,
      ),
      '二段': RankData(
        name: '二段',
        songIds: ['11115', '11437', '11447', '11185'],
        levelIndexes: [1, 1, 1, 1],
        initialHp: 350,
        greatDamage: 0,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 20,
      ),
      '三段': RankData(
        name: '三段',
        songIds: ['11325', '647', '11578', '11472'],
        levelIndexes: [1, 1, 1, 1],
        initialHp: 600,
        greatDamage: 1,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '四段': RankData(
        name: '四段',
        songIds: ['11188', '11158', '11137', '11488'],
        levelIndexes: [2, 2, 2, 2],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '五段': RankData(
        name: '五段',
        songIds: ['418', '11608', '11333', '548'],
        levelIndexes: [2, 2, 2, 2],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '六段': RankData(
        name: '六段',
        songIds: ['11591', '681', '11596', '11272'],
        levelIndexes: [2, 2, 2, 3],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '七段': RankData(
        name: '七段',
        songIds: ['11271', '11009', '782', '11609'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '八段': RankData(
        name: '八段',
        songIds: ['11161', '11499', '11465', '11447'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 20,
      ),
      '九段': RankData(
        name: '九段',
        songIds: ['11383', '464', '11514', '11455'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 800,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 30,
      ),
      '十段': RankData(
        name: '十段',
        songIds: ['840', '11541', '11575', '379'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 900,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 30,
      ),
      '真初段': RankData(
        name: '真初段',
        songIds: ['11010', '11008', '586', '136'],
        levelIndexes: [3, 3, 3, 2],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真二段': RankData(
        name: '真二段',
        songIds: ['791', '11572', '11472', '832'],
        levelIndexes: [3, 3, 2, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真三段': RankData(
        name: '真三段',
        songIds: ['11500', '11226', '239', '11608'],
        levelIndexes: [3, 3, 2, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真四段': RankData(
        name: '真四段',
        songIds: ['11435', '581', '11555', '453'],
        levelIndexes: [3, 2, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真五段': RankData(
        name: '真五段',
        songIds: ['11427', '218', '11214', '299'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真六段': RankData(
        name: '真六段',
        songIds: ['800', '11616', '11204', '11296'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真七段': RankData(
        name: '真七段',
        songIds: ['11211', '701', '11140', '740'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真八段': RankData(
        name: '真八段',
        songIds: ['24', '11509', '446', '803'],
        levelIndexes: [4, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真九段': RankData(
        name: '真九段',
        songIds: ['301', '11386', '11300', '11378'],
        levelIndexes: [4, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真十段': RankData(
        name: '真十段',
        songIds: ['365', '11307', '11374', '643'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真皆传': RankData(
        name: '真皆传',
        songIds: ['11165', '11537', '11394', '11379'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 5,
      ),
      '里皆传': RankData(
        name: '里皆传',
        songIds: ['834', '11612', '11662', '11663'],
        levelIndexes: [4, 3, 3, 4],
        initialHp: 10,
        greatDamage: 1,
        goodDamage: 3,
        missDamage: 10,
        healAmount: 0,
      ),
    };

    return rankDataMap[rankName];
  }
}