import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../constant/AppLinks.dart';
import '../constant/CacheKeyConstant.dart';
import '../utils/CurrentDataSourceNotifier.dart';

/// Best50 系列导出图片中复用的「元信息卡片」。
///
/// 顶部 4 行垂直布局（均右对齐）：
///   1. 数据源（落雪 / 水鱼）
///   2. 导出时间（YYYY-MM-DD HH:MM:SS）
///   3. Generated by ChiffonMai
///   4. 交流群（图标 + 「交流群」 + 群号，见 [AppLinks.qqGroupNumber]）
///
/// 由 [Best50ConvertToImgService] 提取而来，供其他 Best50 导出服务复用。
class MetaRowWidget extends StatelessWidget {
  /// 卡片宽度；传 null 时使用默认值 [defaultWidth]。
  final double? width;

  /// 卡片高度。导出服务的姓名框高度通常为 230，因此默认值也是 230，
  /// 让两者并排时视觉等高。
  final double height;

  /// 默认宽度，对应 `Best50ConvertToImgService` 的 1700 容器：
  /// 1700 - 20*2（外层 padding）= 1660
  /// 1660 - 1150（姓名框） - 16（gap）= 494
  static const double defaultWidth = 494.0;
  static const double defaultHeight = 230.0;

  const MetaRowWidget({
    super.key,
    this.width,
    this.height = defaultHeight,
  });

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Map<String, String>>(
      future: _loadMetaInfo(),
      builder: (context, snapshot) {
        final dataSource = snapshot.data?['dataSource'] ?? '';
        final exportTime = snapshot.data?['exportTime'] ?? '';
        return Container(
          width: width ?? defaultWidth,
          height: height,
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border.all(color: Colors.black, width: 2.0),
            borderRadius: BorderRadius.circular(8.0),
          ),
          padding: const EdgeInsets.fromLTRB(14, 12, 14, 12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: [
              _buildMetaLine(
                icon: Icons.storage_rounded,
                label: '数据源',
                value: dataSource.isNotEmpty ? dataSource : '未知',
              ),
              const SizedBox(height: 8),
              _buildMetaLine(
                icon: Icons.schedule_rounded,
                label: '导出时间',
                value: exportTime,
              ),
              const SizedBox(height: 8),
              Row(
                mainAxisSize: MainAxisSize.min,
                children: const [
                  Icon(Icons.auto_awesome,
                      size: 20, color: Color(0xFF1F4FA5)),
                  SizedBox(width: 6),
                  Text(
                    'Generated by ',
                    style: TextStyle(
                      fontSize: 20,
                      color: Color(0xFF1F4FA5),
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  Text(
                    'ChiffonMai',
                    style: TextStyle(
                      fontSize: 22,
                      color: Color(0xFF1F4FA5),
                      fontWeight: FontWeight.w900,
                      fontStyle: FontStyle.italic,
                      letterSpacing: 0.5,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              _buildQqGroupChip(),
            ],
          ),
        );
      },
    );
  }

  /// 交流群号 — 纯文本展示（无背景框），跟其他 metaRow 文字风格一致。
  static Widget _buildQqGroupChip() {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: const [
        Icon(Icons.chat_bubble_outline,
            size: 22, color: Color(0xFF1F4FA5)),
        SizedBox(width: 6),
        Text(
          '交流群',
          style: TextStyle(
            fontSize: 22,
            color: Color(0xFF1F4FA5),
            fontWeight: FontWeight.w600,
          ),
        ),
        SizedBox(width: 10),
        Text(
          AppLinks.qqGroupNumber,
          style: TextStyle(
            fontSize: 28,
            color: Color(0xFF1F4FA5),
            fontWeight: FontWeight.w900,
            letterSpacing: 1.5,
            fontFeatures: [FontFeature.tabularFigures()],
          ),
        ),
      ],
    );
  }

  /// 单行元数据：图标 + 标签 + 值。
  static Widget _buildMetaLine({
    required IconData icon,
    required String label,
    required String value,
  }) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 20, color: const Color(0xFF555555)),
        const SizedBox(width: 6),
        Text(
          '$label: ',
          style: const TextStyle(
            fontSize: 22,
            color: Colors.black87,
            fontWeight: FontWeight.w600,
          ),
        ),
        Flexible(
          child: Text(
            value,
            style: const TextStyle(
              fontSize: 22,
              color: Colors.black,
              fontWeight: FontWeight.w900,
            ),
            overflow: TextOverflow.ellipsis,
            maxLines: 1,
          ),
        ),
      ],
    );
  }

  /// 异步加载元数据信息（数据源 + 导出时间）。
  static Future<Map<String, String>> _loadMetaInfo() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final dataSource = RefreshDataSource.displayNameOfKey(
          prefs.getString(CacheKeyConstant.lastDataSource));
      final now = DateTime.now();
      final exportTime =
          '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} '
          '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}:${now.second.toString().padLeft(2, '0')}';
      return {
        'dataSource': dataSource,
        'exportTime': exportTime,
      };
    } catch (e) {
      return {'dataSource': '', 'exportTime': ''};
    }
  }
}
