import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../constant/AppLinks.dart';
import '../../constant/CacheKeyConstant.dart';
import '../../utils/CurrentDataSourceNotifier.dart';
import '../../utils/ExportUserInfoWidget.dart';
import '../../widgets/B50GameCardWidget.dart';

/// 雷霆长图：保持单卡的导出尺寸，个人信息、统计和元信息合并成紧凑的说明卡。
/// 横版说明卡放在队首，竖版放在顶部，全部谱面连续排列而不再分成两个网格。
class ThunderBest50Export {
  static const double cardWidth = 335;
  static const double gap = 6;
  static const double verticalWidth = 375;

  static double widthFor(int count, bool vertical) => vertical
      ? verticalWidth
      : 40 + verticalWidth + gap + count * (cardWidth + gap);

  static Future<Widget> build({
    required String title,
    required bool vertical,
    required int count,
    required Widget Function(int index) cardBuilder,
    required String statistics,
    bool showUserInfo = true,
    String? warning,
    String? sortLabel,
  }) async {
    final user = showUserInfo
        ? await ExportUserInfoWidget.loadUserInfo()
        : <String, dynamic>{};
    final prefs = await SharedPreferences.getInstance();
    final source = RefreshDataSource.displayNameOfKey(
        prefs.getString(CacheKeyConstant.lastDataSource));
    final now = DateTime.now();
    final time = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} '
        '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}';
    final avatar = user['avatarUrl'] as String? ?? '';
    final info = Container(
      width: vertical ? cardWidth : verticalWidth,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: const Color(0xFF6750A4)),
        borderRadius: BorderRadius.circular(12),
      ),
      child: DefaultTextStyle(
        style: const TextStyle(color: Color(0xFF252033), fontSize: 16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: const TextStyle(fontSize: 23, fontWeight: FontWeight.bold)),
            const Text('雷霆模式', style: TextStyle(fontSize: 13, color: Color(0xFF6750A4))),
            if (showUserInfo) ...[
              const SizedBox(height: 12),
              Row(children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(10),
                  child: avatar.isEmpty
                      ? const SizedBox(width: 56, height: 56, child: Icon(Icons.person, size: 40))
                      : CachedNetworkImage(imageUrl: avatar, width: 56, height: 56, fit: BoxFit.cover),
                ),
                const SizedBox(width: 10),
                Expanded(child: Text('${user['nickname'] ?? ''}',
                    style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w600))),
              ]),
            ],
            const SizedBox(height: 12),
            Text(statistics),
            if (sortLabel != null && sortLabel.isNotEmpty) Text('排序：$sortLabel'),
            if (warning != null && warning.isNotEmpty)
              Text(warning, style: const TextStyle(color: Color(0xFFB3261E))),
            const Padding(padding: EdgeInsets.symmetric(vertical: 8), child: Divider()),
            Text('数据源：$source\n导出时间：$time\nGenerated by ChiffonMai\n交流群：${AppLinks.qqGroupNumber}',
                style: const TextStyle(fontSize: 12, height: 1.5)),
          ],
        ),
      ),
    );
    final cards = List.generate(count, (index) => SizedBox(
      width: cardWidth,
      height: cardWidth / B50GameCardWidget.designAspectRatio,
      child: cardBuilder(index),
    ));
    return Container(
      width: widthFor(count, vertical),
      padding: const EdgeInsets.all(20),
      color: const Color(0xFFF2ECFA),
      child: vertical
          ? Column(mainAxisSize: MainAxisSize.min, children: [
              info,
              for (final card in cards) ...[const SizedBox(height: gap), card],
            ])
          : Row(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [
              info,
              for (final card in cards) ...[const SizedBox(width: gap), card],
            ]),
    );
  }
}
